#Url Path ans baseurl
url: https://jramos92.github.io/

# Site settings
title: JR Consulting
email: ramos.marin92@gmail.com
description: "Professional software development and consulting services."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1a237e
  secondary: 42a5f5
  secondary-dark: 1565c0

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jramos92?tab=repositories
  - title: envelope-o
    url: mailto:ramos.marin92@gmail.com
  - title: linkedin
    url: https://es.linkedin.com/pub/julian-ramos/b0/ab6/b8b
    
# Build settings
markdown: kramdown
permalink: pretty

# Jekyll multiple languages plugin settings:
languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

# Default language
lang: en
